/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UT6R;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author usuario
 */
public class FrameFiguresFull extends javax.swing.JFrame {
    ArrayList<Drawable> figures=new ArrayList<>();
    /**
     * Creates new form FrameMoveFigures
     */
    public FrameFiguresFull() {
        initComponents();
        figures.add(new Rectangle(Color.BLUE, 10, 40, 50, 50));
        figures.add(new Rectangle(Color.RED, 10, 110, 50, 50));
        figures.add(new Line(Color.YELLOW,70 , 180, 140, 180));
        figures.add(new Line(Color.MAGENTA,70 , 200, 140, 200));
        //figures.add(new Triangle(Color.BLUE, 250,200,280,200,250,100));
        figures.add(new Triangle(Color.ORANGE, 200,200,300,200,250,100));
        figures.add(new Oval(Color.RED, 150,300,200,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonL = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonZL = new javax.swing.JButton();
        jButtonZR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonTL = new javax.swing.JButton();
        jButtonTR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonL.setText("<<");
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonR.setText(">>");
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Desplazar");

        jButtonZL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonZL.setText("+");
        jButtonZL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZLActionPerformed(evt);
            }
        });

        jButtonZR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonZR.setText("-");
        jButtonZR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZRActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Zoom");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thickness");

        jButtonTL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonTL.setText("+");
        jButtonTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTLActionPerformed(evt);
            }
        });

        jButtonTR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonTR.setText("-");
        jButtonTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 558, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonR)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonZR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonZL)
                            .addGap(28, 28, 28))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonTR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonTL))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonL)
                    .addComponent(jButtonR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZL)
                    .addComponent(jButtonZR))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTL)
                    .addComponent(jButtonTR))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        for (Drawable drawable : figures) {
            drawable.moverDerecha();
        }
        repaint();
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        for (Drawable drawable : figures) {
            drawable.moverIzquierda();
        }
        repaint();
    }//GEN-LAST:event_jButtonLActionPerformed

    private void jButtonZRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZRActionPerformed
        GeometricalFigure.zoom=GeometricalFigure.zoom-1;
        repaint();
    }//GEN-LAST:event_jButtonZRActionPerformed

    private void jButtonZLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZLActionPerformed
        GeometricalFigure.zoom=GeometricalFigure.zoom+1;
        repaint();
    }//GEN-LAST:event_jButtonZLActionPerformed
        
    private void jButtonTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTRActionPerformed
        GeometricalFigure.thickness=GeometricalFigure.thickness-1;
        repaint();
    }//GEN-LAST:event_jButtonTRActionPerformed

    private void jButtonTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTLActionPerformed
        GeometricalFigure.thickness=GeometricalFigure.thickness+1;
        repaint();
    }//GEN-LAST:event_jButtonTLActionPerformed

    public void paint(Graphics g) {
        //realiza operaciones de pintado estándar, como borrar el contenido anterior de la ventana
        super.paint(g);
        //Graphics2D g2d = (Graphics2D) g; // Convertimos Graphics a Graphics2D
        for (Drawable figure : figures) {
            figure.draw(g);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFiguresFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFiguresFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFiguresFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFiguresFull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFiguresFull().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonTL;
    private javax.swing.JButton jButtonTR;
    private javax.swing.JButton jButtonZL;
    private javax.swing.JButton jButtonZR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
